# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "Version-*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
          flutter-version: 3.22.0
      - name: Install dependencies
        run: flutter pub get
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
